# Generated by Django 3.1.2 on 2020-10-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceCustomerData',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed Substance', max_length=250)),
                ('brand_name', models.CharField(default='Not Available', max_length=250)),
                ('regular_price_value', models.FloatField(default=0)),
                ('offer_price_value', models.FloatField(default=0)),
                ('currency', models.CharField(default='GBP', max_length=50)),
                ('classification_l1', models.CharField(blank=True, max_length=250)),
                ('classification_l2', models.CharField(blank=True, max_length=250)),
                ('classification_l3', models.CharField(blank=True, max_length=250)),
                ('classification_l4', models.CharField(blank=True, max_length=250)),
                ('image_url', models.URLField(default='Not Available', max_length=250)),
            ],
        ),
    ]
